### ISSUE TITLE
Travis build fails to respond after integrating GUI test 

### ISSUE THREAD

**Issue by EugeneTeu** [nus-cs2103-AY1920S1/forum#141]
## Environment

Describe your development environment

- IntelliJ version: 11.0.3
- Java version: java 11 2018-09-25
- Operating system version: MacOs
- _other packages' versions_

## Issue

Hey guys I integrated the GUI tests from AB4 and wrote some unit tests. On my local terminal, everything works fine (all tests pass) and check style passes but somehow on Travis, the build stalls after starting the GUI tests. 

This causes Travis to trigger an error message stating that there's no output. 

Was wondering if anyone has ran into this issue when setting up their GUI test.

## Code/Log Trace

For code, you can link to your branch on GitHub. For short code snippets, you can copy and paste in code block:

[link to failing PR Build](https://github.com/AY1920S1-CS2103T-T09-4/main/pull/139)

[link to my branch](https://github.com/EugeneTeu/main/tree/GUI-tests)

This is the log from the Travis build. 
```
 seedu.address.ui.CustomerListPanelTest > performanceTest() STARTED

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated

```

The fix that travis directs me to is to simply wait for longer (right now the build terminates after 10 mins)but as my tests are working fine, its probably an issue of me not integrating the gui test properly with travis.

 I have also tried manually running the Gradle method that travis runs and it works fine on my local terminal! 

Will appreciate it if someone could point me in the right direction

**Comment by damithc** [comment]
Are you able to run tests locally in headless mode? See https://se-education.org/addressbook-level4/Testing.html

**Comment by EugeneTeu** [comment]
yes. 

My output is this, ignoring ascii doctor warnings: 
<img width="1336" alt="Screenshot 2019-10-23 at 5 24 15 PM" src="https://user-images.githubusercontent.com/43085751/67378582-0fd74880-f5ba-11e9-8153-a3cb5a01645e.png">

**Comment by j-lum** [comment]
Doesn't look fun to debug but I highly suspect it has something to do with thread pooling done behind the scenes by JUnit. You might want to explicitly configure them to avoid strange behavior.

**Comment by EugeneTeu** [comment]
Good news! found a fix for this: 
enabling xvfb mode to run before the script in the travis.yml file seems to fix it, under `services` and the `before_script` section. My build successfully pass after including that. 

```
language: java
matrix:
  include:
    - jdk: openjdk11
services:
  - xvfb

before_script:
  - export DISPLAY=:99.0

script: >-
    ./config/travis/run-checks.sh &&
    ./gradlew clean checkstyleMain checkstyleTest test coverage coveralls asciidoctor

deploy:
  skip_cleanup: true
  provider: script
  script: ./config/travis/deploy_github_pages.sh
  on:
    branch: master

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
```

[From official documentation](https://docs.travis-ci.com/user/gui-and-headless-browsers/)

Hopefully anyone else wanting to integrate GUI-tests into their TP can refer to this fix if their tests fail too!
